#!/usr/bin/env python3
"""Patch vice-libretro before compilation to require external firmware.

The normal vice-libretro build compiles generated C headers containing both
firmware payloads and non-firmware resources such as VIC-II palettes. POKE64
must preserve the latter while ensuring that proprietary firmware bytes are not
present in the resulting core.

This script patches the fetched source tree *before* compilation:

1. define POKE64_EXTERNAL_FIRMWARE_ONLY in vice/src/sysfile.c;
2. replace embedded_check_file(...) with a compile-time zero-result macro in
   that translation unit, so existing call sites fall through to filesystem
   lookup;
3. disable libretro-only declarations in sysfile.c that expose the embedded
   firmware lookup implementation;
4. keep include/embedded on the compiler include path because palette headers
   and other non-firmware generated resources require it;
5. locate generated byte arrays that exactly match C64/drive firmware files and
   replace only those array payloads with zero bytes before compilation;
6. write a JSON report describing every source-level change.

The script fails closed if it cannot identify BASIC, KERNAL, character and drive
firmware payloads in the generated headers.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

DEFINE_NAME = "POKE64_EXTERNAL_FIRMWARE_ONLY"
FIRMWARE_SIZES = {4096, 8192, 16384, 32768, 65536}
REQUIRED_CATEGORIES = {"basic", "kernal", "chargen", "drive"}


@dataclass
class ConditionalBlock:
    start: int
    end: int
    opening: str
    body: str


@dataclass
class FirmwareCandidate:
    digest: str
    payload: bytes
    paths: list[str] = field(default_factory=list)
    categories: set[str] = field(default_factory=set)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def category_for(path: Path, data_root: Path) -> set[str]:
    relative = path.relative_to(data_root)
    name = path.name.lower()
    categories: set[str] = set()
    if relative.parts and relative.parts[0].upper() == "DRIVES":
        categories.add("drive")
    if "basic" in name:
        categories.add("basic")
    if "kernal" in name or "kernel" in name:
        categories.add("kernal")
    if "chargen" in name or "character" in name:
        categories.add("chargen")
    return categories


def collect_firmware_candidates(source: Path) -> dict[str, FirmwareCandidate]:
    data_root = source / "vice" / "data"
    candidates: dict[str, FirmwareCandidate] = {}
    found_categories: set[str] = set()

    for search_root in (data_root / "C64", data_root / "DRIVES"):
        if not search_root.is_dir():
            raise RuntimeError(f"Expected firmware directory not found: {search_root}")
        for path in sorted(search_root.rglob("*")):
            if not path.is_file() or path.stat().st_size not in FIRMWARE_SIZES:
                continue
            categories = category_for(path, data_root)
            if not categories:
                continue
            payload = path.read_bytes()
            digest = hashlib.sha256(payload).hexdigest()
            candidate = candidates.setdefault(
                digest,
                FirmwareCandidate(digest=digest, payload=payload),
            )
            candidate.paths.append(str(path.relative_to(source)))
            candidate.categories.update(categories)
            found_categories.update(categories)

    missing = REQUIRED_CATEGORIES - found_categories
    if missing:
        raise RuntimeError(
            "Unable to build a complete firmware candidate set; missing categories: "
            + ", ".join(sorted(missing))
        )
    return candidates


def embedded_tokens(directory: Path) -> set[str]:
    if not directory.is_dir():
        raise RuntimeError(f"Embedded header directory not found: {directory}")

    tokens: set[str] = {"embedded", "embedded_rom", "embeddedrom"}
    headers = sorted(directory.glob("*.h"))
    if not headers:
        raise RuntimeError(f"No generated embedded headers found in: {directory}")

    declaration = re.compile(
        r"\b(?:static\s+)?(?:const\s+)?(?:unsigned\s+)?(?:char|uint8_t|BYTE)\s+([A-Za-z_]\w*)"
    )
    macro = re.compile(r"^\s*#\s*define\s+([A-Za-z_]\w*)", re.MULTILINE)

    for header in headers:
        tokens.add(header.name.lower())
        tokens.add(header.stem.lower())
        text = header.read_text(encoding="utf-8", errors="ignore")
        tokens.update(match.group(1).lower() for match in declaration.finditer(text))
        tokens.update(match.group(1).lower() for match in macro.finditer(text))

    return {token for token in tokens if len(token) >= 4}


def conditional_blocks(lines: list[str]) -> list[ConditionalBlock]:
    blocks: list[ConditionalBlock] = []
    stack: list[int] = []
    directive = re.compile(r"^\s*#\s*(if|ifdef|ifndef|endif)\b")

    for index, line in enumerate(lines):
        match = directive.match(line)
        if not match:
            continue
        kind = match.group(1)
        if kind in {"if", "ifdef", "ifndef"}:
            stack.append(index)
        elif kind == "endif":
            if not stack:
                raise RuntimeError("Unbalanced preprocessor #endif in sysfile.c")
            start = stack.pop()
            blocks.append(
                ConditionalBlock(
                    start=start,
                    end=index,
                    opening=lines[start],
                    body="".join(lines[start : index + 1]),
                )
            )

    if stack:
        raise RuntimeError("Unbalanced preprocessor conditional in sysfile.c")
    return blocks


def is_libretro_guard(opening: str) -> bool:
    normalized = opening.replace(" ", "")
    return "__LIBRETRO__" in normalized and normalized.lstrip().startswith("#")


def is_embedded_block(block: ConditionalBlock, tokens: set[str]) -> bool:
    body = block.body.lower()
    if "include/embedded" in body:
        return True
    if re.search(r"#\s*include\s*[<\"][^>\"]*(?:basic|kernal|chargen|dos)[^>\"]*[>\"]", body):
        return True
    return any(token in body for token in tokens)


def rewritten_guard(opening: str) -> str:
    newline = "\n" if opening.endswith("\n") else ""
    stripped = opening.rstrip("\n")
    indent = stripped[: len(stripped) - len(stripped.lstrip())]
    content = stripped.strip()

    if DEFINE_NAME in content:
        return opening
    if re.fullmatch(r"#\s*ifdef\s+__LIBRETRO__", content):
        return f"{indent}#if defined(__LIBRETRO__) && !defined({DEFINE_NAME}){newline}"
    if re.fullmatch(r"#\s*if\s+defined\s*\(\s*__LIBRETRO__\s*\)", content):
        return f"{indent}#if defined(__LIBRETRO__) && !defined({DEFINE_NAME}){newline}"
    if content.startswith("#if"):
        expression = re.sub(r"^#\s*if\s*", "", content, count=1)
        return f"{indent}#if !defined({DEFINE_NAME}) && ({expression}){newline}"
    raise RuntimeError(f"Unsupported libretro preprocessor guard: {content}")


def insert_define(lines: list[str]) -> int:
    marker = f"#define {DEFINE_NAME} 1"
    override = "#define embedded_check_file(...) 0"
    if any(marker in line for line in lines):
        if not any(override in line for line in lines):
            raise RuntimeError(
                "External-firmware marker already exists but the "
                "embedded_check_file override is missing."
            )
        return -1

    injected = (
        "\n/* POKE64: require firmware from the frontend system directory. */\n"
        f"{marker}\n"
        "/* Existing sysfile call sites must fall through to filesystem lookup. */\n"
        f"{override}\n"
    )

    for index, line in enumerate(lines):
        if re.match(r'^\s*#\s*include\s+[<\"]vice\.h[>\"]', line):
            lines.insert(index + 1, injected)
            return index + 1

    for index, line in enumerate(lines):
        if re.match(r"^\s*#\s*include\b", line):
            lines.insert(index, injected.lstrip("\n") + "\n")
            return index
    raise RuntimeError("Unable to locate an include section in sysfile.c")


def patch_sysfile(sysfile: Path, tokens: set[str]) -> dict[str, object]:
    original_hash = sha256(sysfile)
    lines = sysfile.read_text(encoding="utf-8").splitlines(keepends=True)
    define_line = insert_define(lines)

    blocks = conditional_blocks(lines)
    candidates = [
        block
        for block in blocks
        if is_libretro_guard(block.opening) and is_embedded_block(block, tokens)
    ]
    if not candidates:
        libretro_guards = [block.opening.strip() for block in blocks if is_libretro_guard(block.opening)]
        raise RuntimeError(
            "No libretro embedded-firmware block was recognized in vice/src/sysfile.c. "
            "Upstream source layout may have changed. Detected libretro guards: "
            + repr(libretro_guards)
        )

    patched_guards: list[dict[str, object]] = []
    for block in sorted(candidates, key=lambda item: item.start, reverse=True):
        before = lines[block.start].rstrip("\n")
        lines[block.start] = rewritten_guard(lines[block.start])
        after = lines[block.start].rstrip("\n")
        patched_guards.append({"line": block.start + 1, "before": before, "after": after})

    sysfile.write_text("".join(lines), encoding="utf-8")
    return {
        "path": str(sysfile),
        "sha256_before": original_hash,
        "sha256_after": sha256(sysfile),
        "define_inserted_at_line": None if define_line < 0 else define_line + 1,
        "embedded_check_file_override": "#define embedded_check_file(...) 0",
        "patched_guard_count": len(patched_guards),
        "patched_guards": list(reversed(patched_guards)),
    }


ARRAY_PATTERN = re.compile(
    r"(?P<prefix>"
    r"(?:static\s+)?(?:const\s+)?(?:unsigned\s+)?"
    r"(?:char|uint8_t|BYTE)\s+[A-Za-z_]\w*\s*"
    r"(?:\[[^\]]*\])?\s*=\s*\{)"
    r"(?P<body>.*?)"
    r"(?P<suffix>\}\s*;)",
    re.DOTALL,
)
NUMBER_PATTERN = re.compile(r"(?<![A-Za-z0-9_.])(?:0[xX][0-9A-Fa-f]+|\d+)(?![A-Za-z0-9_.])")
COMMENT_PATTERN = re.compile(r"/\*.*?\*/|//[^\n]*", re.DOTALL)


def numeric_bytes(text: str) -> bytes | None:
    without_comments = COMMENT_PATTERN.sub("", text)
    tokens = NUMBER_PATTERN.findall(without_comments)
    if not tokens:
        return None
    values: list[int] = []
    for token in tokens:
        value = int(token, 0)
        if value > 255:
            return None
        values.append(value)
    return bytes(values)


def zero_body(length: int) -> str:
    values = ["0x00"] * length
    rows = [", ".join(values[index : index + 16]) for index in range(0, length, 16)]
    return "\n    " + ",\n    ".join(rows) + "\n"


def neutralize_header(
    header: Path,
    by_payload: dict[bytes, FirmwareCandidate],
) -> tuple[str, list[dict[str, object]]]:
    original = header.read_text(encoding="utf-8", errors="strict")
    replacements: list[dict[str, object]] = []

    def replace_array(match: re.Match[str]) -> str:
        payload = numeric_bytes(match.group("body"))
        if payload is None or payload not in by_payload:
            return match.group(0)
        candidate = by_payload[payload]
        replacements.append(
            {
                "sha256": candidate.digest,
                "size": len(candidate.payload),
                "categories": sorted(candidate.categories),
                "source_paths": candidate.paths,
            }
        )
        return match.group("prefix") + zero_body(len(payload)) + match.group("suffix")

    updated = ARRAY_PATTERN.sub(replace_array, original)

    # Some generated headers may contain only a raw comma-separated initializer
    # fragment. Handle that format only when the entire numeric payload matches a
    # known firmware file; palette and other headers remain untouched.
    if not replacements:
        payload = numeric_bytes(original)
        if payload is not None and payload in by_payload:
            candidate = by_payload[payload]
            matches = list(NUMBER_PATTERN.finditer(COMMENT_PATTERN.sub("", original)))
            if not matches:
                raise RuntimeError(f"Unable to neutralize raw firmware header: {header}")
            # Raw generated headers are expected to contain only numeric data and
            # separators. Rebuild as a valid comma-separated fragment.
            updated = zero_body(len(payload)).strip() + "\n"
            replacements.append(
                {
                    "sha256": candidate.digest,
                    "size": len(candidate.payload),
                    "categories": sorted(candidate.categories),
                    "source_paths": candidate.paths,
                    "raw_fragment": True,
                }
            )

    if replacements:
        header.write_text(updated, encoding="utf-8")
    return original, replacements


def neutralize_firmware_headers(
    embedded_dir: Path,
    candidates: dict[str, FirmwareCandidate],
) -> dict[str, object]:
    by_payload = {candidate.payload: candidate for candidate in candidates.values()}
    changed_headers: list[dict[str, object]] = []
    detected_categories: set[str] = set()

    for header in sorted(embedded_dir.glob("*.h")):
        before_hash = sha256(header)
        _original, replacements = neutralize_header(header, by_payload)
        if not replacements:
            continue
        for replacement in replacements:
            detected_categories.update(replacement["categories"])
        changed_headers.append(
            {
                "path": str(header),
                "sha256_before": before_hash,
                "sha256_after": sha256(header),
                "neutralized_arrays": replacements,
            }
        )

    missing = REQUIRED_CATEGORIES - detected_categories
    if missing:
        raise RuntimeError(
            "Generated firmware headers could not be neutralized completely; "
            "missing categories: " + ", ".join(sorted(missing))
        )

    return {
        "embedded_include_path_preserved": True,
        "changed_header_count": len(changed_headers),
        "detected_categories": sorted(detected_categories),
        "changed_headers": changed_headers,
    }


def verify_makefile_include_path(makefile: Path) -> dict[str, object]:
    text = makefile.read_text(encoding="utf-8")
    count = len(re.findall(r"-I\$\(CORE_DIR\)/include/embedded\b", text))
    if count != 1:
        raise RuntimeError(
            "Expected exactly one include/embedded search path in Makefile.common; "
            f"found {count}."
        )
    return {
        "path": str(makefile),
        "sha256": sha256(makefile),
        "embedded_include_paths_preserved": count,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--report", required=True, type=Path)
    args = parser.parse_args()

    source = args.source.resolve()
    sysfile = source / "vice" / "src" / "sysfile.c"
    makefile = source / "Makefile.common"
    embedded = source / "include" / "embedded"
    for required in (sysfile, makefile):
        if not required.is_file():
            raise RuntimeError(f"Expected source file not found: {required}")

    candidates = collect_firmware_candidates(source)
    tokens = embedded_tokens(embedded)
    report = {
        "mode": "source-level external firmware only",
        "define": DEFINE_NAME,
        "sysfile": patch_sysfile(sysfile, tokens),
        "embedded_headers": neutralize_firmware_headers(embedded, candidates),
        "makefile": verify_makefile_include_path(makefile),
        "embedded_token_count": len(tokens),
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Applied source-level external firmware patch. Report: {args.report}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:  # noqa: BLE001 - command-line diagnostics
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
